development:
  adapter: postgresql
  encoding: unicode
  database: myfitlist_development
  pool: 5
  username: 
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: myfitlist_test
  pool: 5
  username: 
  password: 
